title: Asher Maes 
description: A portfolio showcasing technical writing and coding projects by Jack Dippel.
baseurl: ""
url: "https://SkyVenture112.github.io" # replace with your GitHub Pages URL
theme: minima  # You can choose another theme or omit this if you’re building custom layouts
